### ISSUE TITLE
Cant Map Controller Input.

### ISSUE THREAD

**Issue by 83RL** [Tgxcorporation/skin.nebula#11]
Sorry. Not sure if you are already aware of this or not.

its minor but..
When you go into Settings > system >  Input  and try to select the "Configure attached controllers: option it doesn't return.  you have to change skin to configure.

**Comment by Tgxcorporation** [comment]
Yes, i’m going to fix it in one of the next commits.

Thanks

**Comment by Tgxcorporation** [comment]
Done in the latest commit!

Thanks

**Comment by 83RL** [comment]
you rock!   i just installed master branch and wow!   total overhaul!  its great!
