### ISSUE TITLE
No program information when switching channel (PVR)

### ISSUE THREAD

**Issue by bizziebis** [Tgxcorporation/skin.nebula#14]
When switching TV channels I would expect to see the channel's program data for 5 seconds (as I set in PVR settings). The dialog does not show up. With the same settings, and the default skin, it works. 

**Skin:** Nebula 5.0.0 / 5.5.0
**Kodi:** 17.6 Krypton
**OS:** Windows 10 + LibreElec + Android 7.1

**Comment by Tgxcorporation** [comment]
Should be fixed now.

Thanks
