### ISSUE TITLE
support for media flags whild using disc stubs

### ISSUE THREAD

**Issue by Theodin** [Tgxcorporation/skin.nebula#4]
First let me say I really like your skin!
While using it, I discovered that dvds I have added to xbmc as disc stubs (http://kodi.wiki/view/Media_stubs) dont get the corresponding dvd icon. The film name/rating/year etc from the filmtitle.nfo show up but the dvd, codecs, rating etc (displayed below the cover on the left side in the list view are missing.
Can you make Nebula display them too?

**Comment by Tgxcorporation** [comment]
Is there any skin which displays those infos with media stubs?
I think this is not possible because how can a skin display an info if it's not available? 
A media stub is an empty file and does not carry the infos about resolution, audio code, channels, etc. It's only a name of an empty file. I think that if the skin does not display the corresponding media logos, it's normal.

**Comment by Theodin** [comment]
In the Confluence theme, its possible to get the DVD/Bluray by putting the folder with the stub (and others) into a folder called "DVD" so it can get the info from there.
I will try to get some illustrating screenshots from my Kodi/Raspberry Pi and post them here to make my point clearer.

**Comment by Theodin** [comment]
Here are some screenshots:
Bluray, DVD and VHS represent the folder name, which is conveniently displayed as a little symbol below the cover. But not if the stub (*.disc) is used.

![bluray_file](https://cloud.githubusercontent.com/assets/8019309/10027881/af67208a-6169-11e5-9d59-ae61978482da.jpg)
![bluray_stub](https://cloud.githubusercontent.com/assets/8019309/10027882/af6a794c-6169-11e5-9d0a-cda391ddb2b5.jpg)
![dvd_file](https://cloud.githubusercontent.com/assets/8019309/10027885/af7ae142-6169-11e5-9e95-5e434e0e6f29.jpg)
![dvd_stub](https://cloud.githubusercontent.com/assets/8019309/10027883/af73a878-6169-11e5-82dd-e6a045d433bd.jpg)
![vhs_file](https://cloud.githubusercontent.com/assets/8019309/10027886/af82ac06-6169-11e5-910c-e653af80218c.jpg)
![vhs_stub](https://cloud.githubusercontent.com/assets/8019309/10027884/af76b400-6169-11e5-9f80-002a8a7fcac2.jpg)

The same goes for the age-rating (PG, R etc, I use the german ones) which is present in the nfo but not displayed on screen below the cover. Besides, would it be possible to somehow parse the age rating and just display the "12" instead of "germany:12"?
Thanks for your time.

**Comment by Tgxcorporation** [comment]
Ok. I understand your point. 
Could you please post a screenshot of the same stub movie but using the Confluence skin?

**Comment by Theodin** [comment]
Here are the same movies (minus one where the screenshot somehow didnt work) displayed using the confluence skin:

![vhs_stub](https://cloud.githubusercontent.com/assets/8019309/10030427/ea0438dc-6177-11e5-9c93-c0a0c38a6776.jpg)
![vhs_file](https://cloud.githubusercontent.com/assets/8019309/10030428/ea0a9e7a-6177-11e5-898f-5fb37a4e58c0.jpg)
![dvd_stub](https://cloud.githubusercontent.com/assets/8019309/10030430/ea12769a-6177-11e5-935a-c6e479e5d6f5.jpg)
![bluray_stub](https://cloud.githubusercontent.com/assets/8019309/10030431/ea12d39c-6177-11e5-8384-17a5fd06c291.jpg)
![bluray_file](https://cloud.githubusercontent.com/assets/8019309/10030429/ea106b5c-6177-11e5-9747-d6ffea786653.jpg)

**Comment by Tgxcorporation** [comment]
Should be ok now with the latest commits on master and isengard branches.

**Comment by Theodin** [comment]
Wow youre fast! Thanks! I will try this. Do I have to wait for the next skin release to get the update or do I have to download the zip and update manually?

**Comment by Tgxcorporation** [comment]
Install from Github if you don't want to wait. 
No ETA for the official update at the moment.

**Comment by Theodin** [comment]
I tried installing it from the zip downloaded from github, but it said something about missing dependencies. Does the zip require the latest Kodi beta? I am using Isengard/Openelec.

**Comment by Tgxcorporation** [comment]
You need to install the script.skin.helper.service addon which is not yet in the Kodi repository:

https://github.com/marcelveldt/script.skin.helper.service

**Comment by Theodin** [comment]
Yes. And I had to change xbmc.gui to 5.3 to work with Helix. But now it works. Thanks for your fast answer!!!
