### ISSUE TITLE
Nebula breaks search function in flickr and 500px addons

### ISSUE THREAD

**Issue by aliencq** [Tgxcorporation/skin.nebula#5]
Hi,
When I navigate to "search" in flickr or 500px, first it opens input box even before I press "select", then instead of showing search results it starts slideshow on the background.
Nebula 4.5.0, latest Kodi on OpenSUSE and LibreELEC on RPi2. Reproducible on both.
Update: It only works fine when I disable backdrop fanarts completely.

**Comment by Tgxcorporation** [comment]
I cannot get any of these plugin to work even with the default skin. API errors from the addons. 
I think these addons need some fixes...
