### ISSUE TITLE
Skin.Nebula Disable Auto Update

### ISSUE THREAD

**Issue by simontfs** [Tgxcorporation/skin.nebula#6]
Using Linux Ubuntu 17.04 LTS
Kodi version 16.1
Settings>Add-ons>My Add-ons>Look and Feel>Skin>Nebula press the right arrow key>Auto Update>_No Options to disable_
[https://www.dropbox.com/s/1bcuwkivpxlpimx/Nebula-No%20disable%20update.jpg?dl=0](url)
As far as I can see there is no way to disable the skin from updating. 
Possibly a setting in one of the xml files could be added tpo enable manually disabling the auto update

**Comment by Tgxcorporation** [comment]
Kodi should not try to update the skin in this manner especially using Krypton as the only available skin version for Krypton can only be installed by hand from Github. 
Have you installed the skin from Github? https://github.com/Tgxcorporation/skin.nebula/wiki/Install-from-GitHub

**Comment by Tgxcorporation** [comment]
Sorry, forget about Krypton, i was confused by Ubuntu 17.
However i still advice the installation from Github

**Comment by simontfs** [comment]
Ok thanks Tgxcorporation ill install from the github.. Although as in Xonfluence, it would be nice to have the choice to Not update the skin. And thanks for all the work on this skin.
