### ISSUE TITLE
Kodi 18 Official Compatibility?

### ISSUE THREAD

**Issue by 83RL** [Tgxcorporation/skin.nebula#9]
Tried this skin a few months ago and it only worked for 20 seconds then crashed hard and would not reload.   for the short amount of time i did have it working on 18 the graphics were very erratic and glitcy.

i tried again today and its 1000x more stable but still crashing after so long.
graphics are a LOT better as well but there are still these strange square dots down the center of display.

i dont know if you are working towards compatibility or if Kodi getting closer to releasing v18 has aided in the improvement but it is substantially better.

just wanted to let you know its not far off in case you were unaware.

**Comment by 83RL** [comment]
Oh and you are an absolute beast at making Kodi skins.   i knew you created Nebula which is without a doubt the most beautful but you created Black glass and Chroma as well which i would no doubt be using one of the 2 if nebula didnt exist.  pretty much everyone you have made are my favorites.  thank you for the awesome work.

**Comment by Tgxcorporation** [comment]
Do not worry. Nebula is still alive and will work on Kodi 18. A new home menu is in the works bringing all the new features I developed for the Andromeda skin. 
A general graphic refresh is scheduled too.
I'll start working on Leia as soon as a working beta will be available.

**Comment by 83RL** [comment]
awesome!
i haven't seen Andromeda, checking it out immediately.    definitely interested in the direction you are taking Nebula..

**Comment by krash1220** [comment]
I love this skin. I was very disappointed when I installed the Kodi Store App and the skin wasn't available. Will you at any point make it available for the Store App? If not, I will definitely be sticking with the Windows install version. I use your plugin.video.plexbmc-isengard-helper-merge.zip plugin and it is absolutely perfect for plex. I only have to hit one button to have it take me to my plex playlist. Thank you and I can't wait for a new version.

**Comment by Tgxcorporation** [comment]
The development for Leia has started in the master branch. 
Everything should be ok apart from the screens dedicated to retrogaming (coming soon).

Thanks

Tgx

**Comment by Strat1987** [comment]
Is Nebula available for Kodi Leia 18.1? Doesn't pop-up in the list for me and was removed after updating my libreelec. Really looking forward to getting back to using this skin!
